#define COMSIG_VICIOUSLY_MOCKED "viciously_mocked_act" // (victim, user)
#define COMSIG_BAPTISM_RECEIVED "baptism_received" // (baptizer)
#define COMSIG_LUX_EXTRACTED "lux_extracted" // (victim)
#define COMSIG_GLOBAL_MARRIAGE "global_marriage" // (bride, groom)
#define COMSIG_DRUG_SNIFFED "drug_sniffed" // (applier)
#define COMSIG_ITEM_STOLEN "item_stolen" // (victim)
#define COMSIG_SKILL_XP_GAINED "skill_xp_gained" // (skill_type, amount_gained, new_level)
#define COMSIG_SKILL_RANK_INCREASED "skill_rank_increased" // (skill_type, new_rank)
