#define COMSIG_VICIOUSLY_MOCKED "viciously_mocked_act" // (victim, user)
#define COMSIG_BAPTISM_RECEIVED "baptism_received" // (baptizer)
#define COMSIG_LUX_EXTRACTED "lux_extracted" // (victim)
#define COMSIG_GLOBAL_MARRIAGE "global_marriage" // (bride, groom)
#define COMSIG_DRUG_SNIFFED "drug_sniffed" // (applier)
